### ISSUE TITLE
elasticsearch version 5.5.2 error on mac

### ISSUE THREAD

**Issue by gagaboy** [moqui/moqui-elasticsearch#15]
When I update moqui-elasticsearch to the lastest commit on my mac,I got error message below:
`
/Users/mac/developWork/MOQUI/moqui/runtime/base-component/moqui-elasticsearch/home, data at /Users/mac/developWork/MOQUI/moqui/runtime/elasticsearch/data, logs at /Users/mac/developWork/MOQUI/moqui/runtime/log
16:49:33.739 ERROR         main .moqui.i.c.ExecutionContextFactoryImpl Error initializing ToolFactory ElasticSearch
java.lang.IllegalStateException: Unable to initialize modules
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.node.Node.<init>(Node.java:312) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.node.Node.<init>(Node.java:240) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.moqui.elasticsearch.ElasticSearchToolFactory.init(ElasticSearchToolFactory.groovy:95) ~[moqui-elasticsearch-1.1.0.jar:?]
	at org.moqui.impl.context.ExecutionContextFactoryImpl.postFacadeInit(ExecutionContextFactoryImpl.groovy:514) [moqui_temp7667281513814551235WEB-INF_lib_moqui-framework-2.1.0-rc3.jar.:2.1.0-rc3]
	at org.moqui.impl.context.ExecutionContextFactoryImpl.<init>(ExecutionContextFactoryImpl.groovy:226) [moqui_temp7667281513814551235WEB-INF_lib_moqui-framework-2.1.0-rc3.jar.:2.1.0-rc3]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_152-ea]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_152-ea]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_152-ea]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_152-ea]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_152-ea]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380) [?:1.8.0_152-ea]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) [?:1.8.0_152-ea]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) [?:1.8.0_152-ea]
	at org.moqui.Moqui.loadData(Moqui.java:117) [moqui_temp7667281513814551235WEB-INF_lib_moqui-framework-2.1.0-rc3.jar.:2.1.0-rc3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152-ea]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152-ea]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152-ea]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152-ea]
	at MoquiStart.main(MoquiStart.java:141) [moqui.war:?]
Caused by: java.nio.file.FileSystemException: /Users/mac/developWork/MOQUI/moqui/runtime/base-component/moqui-elasticsearch/home/modules/.DS_Store/plugin-descriptor.properties: Not a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_152-ea]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_152-ea]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_152-ea]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_152-ea]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_152-ea]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_152-ea]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_152-ea]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_152-ea]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.plugins.PluginsService.getModuleBundles(PluginsService.java:273) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:117) ~[elasticsearch-5.5.2.jar:5.5.2]
	... 20 more
`
and i find it seems the elasticsearch bug for 5.5.2, which doesn't skip the hidden files from plugin service.The  resolved link is [ https://github.com/elastic/elasticsearch/pull/23982 ](https://github.com/elastic/elasticsearch/pull/23982) . Maybe you can upgrade  or downgrade the version

**Comment by gagaboy** [comment]
Well, I find another way to resolve it, just remove .DS_Stores file in the modules folder on Mac.
And I disabled the DS_Store auto created by MacOX with the command :
`defaults write com.apple.desktopservices DSDontWriteNetworkStores true`

**Comment by jonesde** [comment]
That is an interesting mix of bad behavior. Did you look into whether there is some sort of configuration option for ElasticSearch for this? It may just be a bug that was introduced, ie something like it used to ignore files in the modules directory and now it doesn't. Not much can be done about it in Moqui, it's an ElasticSearch issue, I wouldn't be surprised if there was already be an issue filed for it.

**Comment by jonesde** [comment]
Any follow up on this? I don't think there is anything we can do about it in Moqui, but if you find that there is let me know. Otherwise I'll close this issue.

**Comment by jonesde** [comment]
Closing as part of general cleanup for the move to HiveMind and for no recent activity on this issue. If this comes up again or anyone wants to pursue it feel free to create a request on moqui.org. For more information see:

https://www.moqui.org/m/docs/moqui/Community+Guide
